language: python
python:
    - "2.7"


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
  #- sudo apt-get install -qq python-numpy python-scipy
  #- sudo apt-get install -qq libhdf5-serial-dev python-h5py

# Install packages
install:
  - conda config --add channels primatelang 
  - conda install --yes --file requirements.txt  
  - python setup.py install

#script: 
#    - "./bin/run.sh"
# after_success:
#     coveralls
